name: Infra-Terraform

on:
  push:
    branches: [main] 
  workflow_dispatch:          
    inputs:
      environment:
        type: choice
        options: [prod]
        required: true

permissions:
  id-token: write
  contents: read

env:
  ENV_NAME: ${{ github.event.inputs.environment
    || (github.ref == 'refs/heads/main' && 'dev')
    || 'dev' }}

jobs:
  platform-dev:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.1
      - name: Azure Login Dev
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Terraform Init
        working-directory: ./infra/env/dev/platform
        run: terraform init -reconfigure
        env:
          ARM_USE_OIDC: true
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_RESOURCE_GROUP_NAME: sttfldatatfstate-rg
          ARM_STORAGE_ACCOUNT_NAME: sttfldatatfstate
          ARM_CONTAINER_NAME: sttfldatatfstate-container
          ARM_KEY: tfl-data/dev.tfstate
      - name: Terraform Plan
        working-directory: ./infra/env/dev/platform
        run: terraform plan -out=tfplan
        env:
          ARM_USE_OIDC: true
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Terraform Apply
        working-directory: ./infra/env/dev/platform
        run: terraform apply -auto-approve tfplan
        env:
          ARM_USE_OIDC: true
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  databricks-dev:
    needs: platform-dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.1
      - name: Azure Login Dev
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Terraform Init
        working-directory: ./infra/env/dev/databricks
        run: terraform init -reconfigure
        env:
          ARM_USE_OIDC: true
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_RESOURCE_GROUP_NAME: sttfldatatfstate-rg
          ARM_STORAGE_ACCOUNT_NAME: sttfldatatfstate
          ARM_CONTAINER_NAME: sttfldatatfstate-container
          ARM_KEY: tfl-data/dev-databricks.tfstate
      - name: Terraform Plan
        working-directory: ./infra/env/dev/databricks
        run: terraform plan -out=tfplan
        env:
          ARM_USE_OIDC: true
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Terraform Apply
        working-directory: ./infra/env/dev/databricks
        run: terraform apply -auto-approve tfplan
        env:
          ARM_USE_OIDC: true
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


